apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-e2dj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-e2dj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0073-app
  name: devfile-sample-e2dj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-e2dj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-e2dj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-e2dj@sha256:af49e1fbf212b3a3005ddb091ea22cb1bc2c7705be471966a0c7049df6f00fec
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
